import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const env = createEnv({
  server: {
    NODE_ENV: z.string(),
    PORT: z.string(),
    DATABASE_URL: z.string(),
    TRIGGER_SECRET_KEY: z.string(),
    UPSTASH_REDIS_REST_TOKEN: z.string(),
    UPSTASH_REDIS_REST_URL: z.string(),
    VOYAGE_API_KEY: z.string(),
    ANTHROPIC_API_KEY: z.string(),
    RESEND_API_KEY: z.string(),
    BETTER_AUTH_SECRET: z.string(),
    FACEBOOK_CLIENT_SECRET: z.string(),
    FACEBOOK_CLIENT_ID: z.string(),
    GOOGLE_CLIENT_SECRET: z.string(),
    GOOGLE_CLIENT_ID: z.string(),
    TRIGGER_PROJECT_ID: z.string(),
    ABLY_API_KEY: z.string(),
    BLOB_READ_WRITE_TOKEN: z.string(),
  },
  client: {
    NEXT_PUBLIC_BASE_URL: z.string(),
    NEXT_PUBLIC_STREAM_CLIENT_SECRET: z.string(),
    NEXT_PUBLIC_STREAM_CLIENT_KEY: z.string(),
    NEXT_PUBLIC_ABLY_API_KEY: z.string(),
  },
  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    PORT: process.env.PORT,
    TRIGGER_SECRET_KEY: process.env.TRIGGER_SECRET_KEY,
    DATABASE_URL: process.env.DATABASE_URL,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
    VOYAGE_API_KEY: process.env.VOYAGE_API_KEY,
    ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
    FACEBOOK_CLIENT_SECRET: process.env.FACEBOOK_CLIENT_SECRET,
    FACEBOOK_CLIENT_ID: process.env.FACEBOOK_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    TRIGGER_PROJECT_ID: process.env.TRIGGER_PROJECT_ID,
    ABLY_API_KEY: process.env.ABLY_API_KEY,
    BLOB_READ_WRITE_TOKEN: process.env.BLOB_READ_WRITE_TOKEN,
    NEXT_PUBLIC_STREAM_CLIENT_SECRET: process.env.NEXT_PUBLIC_STREAM_CLIENT_SECRET,
    NEXT_PUBLIC_STREAM_CLIENT_KEY: process.env.NEXT_PUBLIC_STREAM_CLIENT_KEY,
    NEXT_PUBLIC_ABLY_API_KEY: process.env.NEXT_PUBLIC_ABLY_API_KEY,
    NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
  },
});
